name: Build mylib

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: prefix-dev/setup-pixi@v0.9.3
              with:
                  pixi-version: v0.59.0
                  activate-environment: true
            - run: cargo build --release
              working-directory: ./rust/mylib
            - uses: actions/upload-artifact@v5
              with:
                  name: mylib-windows
                  path: ./rust/mylib/target/release/**/*