name: PR
on:
  pull_request:

jobs:
    do-work:
      runs-on: ubuntu-latest
      steps:
      - if: github.event.pull_request.head.repo.full_name == 'jayber-devops/actions-playground'
        run: |
            echo "Hello, World!"
