name: Pixi Update
on:
  workflow_dispatch:

jobs:
    touch-and-push:
      runs-on: ubuntu-latest
      steps:
      - id: get-token
        uses: actions/github-app-token@v2
        with:
          app-id: ${{ secrets.JAYBER_DEVOPS_BOT_CLIENT_ID }}
          private-key: ${{ secrets.JAYBER_DEVOPS_BOT_SECRET }}
      - uses: actions/checkout@v4
      - run: |
            git config --global user.name "github-action [bot]"
            git config --global user.email "arcgis@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${{ steps.get-token.outputs.token }}@github.com/${{ github.repository }}.git
            ts=$(date +%s%3N)
            touch $ts
            git add $ts
            git commit -m "[Automated] Add timestamp"
            git push -f
