name: Release - Upload samples.zip

on:
  release:
    types:
      - published

jobs:
  upload-samples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create samples.zip
        run: |
          zip -r samples.zip samples
      - name: Upload samples.zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            samples.zip